### ISSUE TITLE
[Proposal] A more pythonic binding and rows API

### ISSUE THREAD

**Issue by pfreixes** [pfreixes/acsylla#34]
Acsylla proposes an orthogonal implementation of the CPP API, it means that when the user wants to provide a parameter for a statement needs to provide also the type of the parameter, same when a value from a row is being read.

Another way to do so would be providing a more Pythonic API, which would reproduce similar behavior of the current Python driver.

For making the bindings the user would do something like:

```python
params = {"param1": "foo", "param2": 1}
preapred_statment.bind_dict(params)

params = ["foo", 1]
unpreapred_statment.bind_list(params)
```

Seems that by using the CPP driver the unprepared statement would need to use the `bind_list` method since the setting of a parameter by name is only available for prepared statements [1]

On the other hand, reading rows would not require any type at all neither, so the user could retrieve also column values without having to use the type, for example:

```python
values = [row.column_by_name("value") for row in result.all()]
```

Behind the scenes, Acsylla will figure out the type of the column by using `cass_result_column_type` [2]

# Outstanding questions

- Should we keep the current interface together with the new one? I would prefer to have only a way of biding and reading data, so I would prefer to keep only one implementation

# Concerns

- Types will need to be inferred, once we go beyond the basic types this interface will need to be able to support other types like `custom`, `uuid`, etc
- Subtypes like `int8` or `int64` how they could be differentiated?
- Performance impact, this is a tradeoff and by inferring the type in the critical path would have some impact (needs to be measured)

Type issues could be addressed by providing our own special types, for example

```python
from acsylla import types

statment.bind_dict({"id": 1, "uuid": types.UUID("efefe2f-....")})
```

# Alternatives

Another alternative would be keeping the current API as it is and implementing a new Python data model on top of this. The entry point of this new API would be an instance of a schema provided by the user, for example

```python
class Table(acyslla.data_model.Table):
    id = acsylla.data_model.fields.Int()
    value = acsylla.data_model.fields.Bytes()

cluster = create_cluster(["localhost"])
table = Table(cluster)
prepared = await table.filter(Table.id.eq("?")).prepared()
statement = prepared.bind("id", 1)
await statment.execute()
```

By doing this we will be asking the user explicitly about the schema, which would allow us to provide a more explicit API.

Would this solution solve the concerns around the types expressed in the first proposal?

- Would need to provide its own fields - i.e `fields.UUID()` or `fields.int8` - which most likely would be the same solution that would need to be implemented in the first proposal
- The usage of the data model would impact in some way also in the performance since functions like `prepared.bind` would need to use something dynamic behind the scenes 

[1] https://docs.datastax.com/en/developer/cpp-driver/2.15/api/struct.CassStatement/
[2] https://docs.datastax.com/en/developer/cpp-driver/2.15/api/struct.CassResult/#function-cass_result_column_type

**Comment by fruch** [comment]
I think providing one option is better

My vote is for doing similar automatic typing inference like the python-driver. i.e. to not confuse people with other chooses, and keep specific types like UUID (i.e. that what python-driver is doing)

As for performance wise I don't think it would be a big difference, but lets not speculate, and benchmark and compare the options.

I think having an ORM is nice, but I'm not sure tightly coupling it with the regular API is a good thing, I think it might make things a bit more complex.

**Comment by pfreixes** [comment]
Thanks for the comments @fruch Ill most likely go for the option 1, I'll work on a proposal and see how it works, If the impact is almost negligible I would advocate for making it the unique way of biding or retrieving results for the sake of maintaining less code
